// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

#include <Arduino.h>


uint8_t setBuzzer = 0;

uint8_t current_minute;
uint8_t current_second;
uint8_t gio, phut, giay;

///////////////////// VARIABLES ////////////////////

extern bool flag;
extern uint8_t eventSelect;
extern lv_timer_t * timer;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_Button1_(lv_event_t * e);
lv_obj_t * ui_Button1_;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
//void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
void ui_event_Button2_(lv_event_t * e);
lv_obj_t * ui_Button2_;
void ui_event_Button3_(lv_event_t * e);
lv_obj_t * ui_Button3_;
void ui_event_Button4_(lv_event_t * e);
lv_obj_t * ui_Button4_;
void ui_event_Button5_(lv_event_t * e);
lv_obj_t * ui_Button5_;
void ui_event_Button6_(lv_event_t * e);
lv_obj_t * ui_Button6_;
lv_obj_t * ui_Image2;
lv_obj_t * ui_valueabc;
lv_obj_t * ui_value2;
lv_obj_t * ui_value4_;
lv_obj_t * ui_value3;
lv_obj_t * ui_tim1;
lv_obj_t * ui_tim3;
lv_obj_t * ui_tim2;
lv_obj_t * ui_tim4;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
void ui_event_Button7_(lv_event_t * e);
lv_obj_t * ui_Button7_;
lv_obj_t * ui_Image3_;
lv_obj_t * ui_valueabc3;
lv_obj_t * ui_tim5;
void ui_event_Button34(lv_event_t * e);
lv_obj_t * ui_Button34;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
void ui_event_btnfn(lv_event_t * e);
lv_obj_t * ui_btnfn;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Minute;
lv_obj_t * ui_Second;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_[3] = {&ui_img_1_png, &ui_img_2_png, &ui_img_3_png};
const lv_img_dsc_t * ui_imgset_a[1] = {&ui_img_a1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1_(lv_event_t * e)
{

    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen2_screen_init);
        setBuzzer = 1;
        ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_abcd_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image4, 221);
    lv_obj_set_y(ui_Image4, -118);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image5, &ui_img_ef_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image5, 185);
    lv_obj_set_y(ui_Image5, -117);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

        _ui_screen_delete(&ui_Screen1);
    }
}

void ui_event_Button2_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen3_screen_init);
        setBuzzer = 1;
        eventSelect = 2;
        
        const char * text = lv_label_get_text(ui_valueabc);
        lv_label_set_text(ui_valueabc3, text);
        const char * text1 = lv_label_get_text(ui_tim1);
        lv_label_set_text(ui_tim5,text1);
        
        _ui_screen_delete(&ui_Screen2);
    }
}
void ui_event_Button3_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen3_screen_init);
        setBuzzer = 1;
        const char * text = lv_label_get_text(ui_value4_);
        lv_label_set_text(ui_valueabc3, text);
         const char * text1 = lv_label_get_text(ui_tim3);
        lv_label_set_text(ui_tim5,text1);
        _ui_screen_delete(&ui_Screen2);

        eventSelect = 3;
    }
}
void ui_event_Button4_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen3_screen_init);
        setBuzzer = 1;
       const char * text = lv_label_get_text(ui_value2);
        lv_label_set_text(ui_valueabc3, text);
         const char * text1 = lv_label_get_text(ui_tim2);
        lv_label_set_text(ui_tim5,text1);
        _ui_screen_delete(&ui_Screen2);

        eventSelect = 4;
    }
}
void ui_event_Button5_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen3_screen_init);
        setBuzzer = 1;

      const char * text = lv_label_get_text(ui_value3);
        lv_label_set_text(ui_valueabc3, text);
         const char * text1 = lv_label_get_text(ui_tim4);
        lv_label_set_text(ui_tim5,text1);
        _ui_screen_delete(&ui_Screen2);

        eventSelect = 5;
    }
}
void ui_event_Button6_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
        setBuzzer = 1;
        _ui_screen_delete(&ui_Screen2);
    }
}
void ui_event_Button7_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen2_screen_init);
        setBuzzer = 1;
        _ui_screen_delete(&ui_Screen3);
    }
}
void ui_event_Button34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
          
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen4_screen_init);
        setBuzzer = 1;
            //  if (current_minute >= 1) {
    //      lv_timer_pause(timer);  
    // //     // lv_label_set_text(ui_Minute, "01");  // Hiển thị số 02 trên label phút
    //     // lv_label_set_text(ui_Second, "00");
        
    // }
        _ui_screen_delete(&ui_Screen3);
    }
}
void ui_event_btnfn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen2_screen_init);
        setBuzzer = 1;
        _ui_screen_delete(&ui_Screen4);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
