// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button1_(lv_event_t * e);
extern lv_obj_t * ui_Button1_;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;

extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button2_(lv_event_t * e);
extern lv_obj_t * ui_Button2_;
void ui_event_Button3_(lv_event_t * e);
extern lv_obj_t * ui_Button3_;
void ui_event_Button4_(lv_event_t * e);
extern lv_obj_t * ui_Button4_;
void ui_event_Button5_(lv_event_t * e);
extern lv_obj_t * ui_Button5_;
void ui_event_Button6_(lv_event_t * e);
extern lv_obj_t * ui_Button6_;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_valueabc;
extern lv_obj_t * ui_value2;
extern lv_obj_t * ui_value4_;
extern lv_obj_t * ui_value3;
extern lv_obj_t * ui_tim1;
extern lv_obj_t * ui_tim3;
extern lv_obj_t * ui_tim2;
extern lv_obj_t * ui_tim4;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Button7_(lv_event_t * e);
extern lv_obj_t * ui_Button7_;
extern lv_obj_t * ui_Image3_;
extern lv_obj_t * ui_valueabc3;
extern lv_obj_t * ui_tim5;
void ui_event_Button34(lv_event_t * e);
extern lv_obj_t * ui_Button34;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
void ui_event_btnfn(lv_event_t * e);
extern lv_obj_t * ui_btnfn;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Minute;
extern lv_obj_t * ui_Second;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1_png);    // assets/1.png
LV_IMG_DECLARE(ui_img_abcd_png);    // assets/abcd.png
LV_IMG_DECLARE(ui_img_ef_png);    // assets/ef.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png
LV_IMG_DECLARE(ui_img_a1_png);    // assets/a1.png

extern uint8_t gio, phut, giay;




void ui_init(void);
void saveToEEPROM(const char* valueToSave);
//  readFromEEPROM();
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
