// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
extern uint8_t TotalTimeinSec;

extern lv_obj_t * qrCode;
void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7_ = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button7_, 67);
    lv_obj_set_height(ui_Button7_, 49);
    lv_obj_set_x(ui_Button7_, 104);
    lv_obj_set_y(ui_Button7_, 92);
    lv_obj_set_align(ui_Button7_, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7_, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7_, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3_ = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image3_, &ui_img_3_png);
    lv_obj_set_width(ui_Image3_, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image3_, LV_SIZE_CONTENT);    /// 272
    lv_obj_set_x(ui_Image3_, -1);
    lv_obj_set_y(ui_Image3_, 1);
    lv_obj_set_align(ui_Image3_, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3_, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_valueabc3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_valueabc3, 74);
    lv_obj_set_height(ui_valueabc3, 27);
    lv_obj_set_x(ui_valueabc3, 59);
    lv_obj_set_y(ui_valueabc3, -82);
    lv_obj_set_align(ui_valueabc3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueabc3, "22");
    lv_obj_set_style_text_color(ui_valueabc3, lv_color_hex(0xF5E205), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_valueabc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_valueabc3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_valueabc3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valueabc3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tim5 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_tim5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tim5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tim5, 120);
    lv_obj_set_y(ui_tim5, -85);
    lv_obj_set_align(ui_tim5, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_tim5, lv_color_hex(0x0307A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tim5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tim5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tim5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button34 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button34, 100);
    lv_obj_set_height(ui_Button34, 50);
    lv_obj_set_x(ui_Button34, -138);
    lv_obj_set_y(ui_Button34, -19);
    lv_obj_set_align(ui_Button34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button7_, ui_event_Button7_, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button34, ui_event_Button34, LV_EVENT_ALL, NULL);
   qrCode = lv_qrcode_create(ui_Screen3, 200, lv_color_hex3(0x000), lv_color_hex3(0xeef));
}
